// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_CXuX6tsA6HVcELZYqqFkvBd6CLkRXFw',
    appId: '1:274695164037:web:60e323332993061b9e59ec',
    messagingSenderId: '274695164037',
    projectId: 'bilal-store-237cd',
    authDomain: 'bilal-store-237cd.firebaseapp.com',
    storageBucket: 'bilal-store-237cd.appspot.com',
    measurementId: 'G-2V1V2L7VLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEQLNBAogRiXqtAUaIRHkWmPN0BbISnYk',
    appId: '1:274695164037:android:186de9d8f1281a4b9e59ec',
    messagingSenderId: '274695164037',
    projectId: 'bilal-store-237cd',
    storageBucket: 'bilal-store-237cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUwOMJQfpX4AVawkIPy6riR5qGOxt6whk',
    appId: '1:274695164037:ios:be849764fbfdde5f9e59ec',
    messagingSenderId: '274695164037',
    projectId: 'bilal-store-237cd',
    storageBucket: 'bilal-store-237cd.appspot.com',
    iosBundleId: 'com.example.bilalStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUwOMJQfpX4AVawkIPy6riR5qGOxt6whk',
    appId: '1:274695164037:ios:be849764fbfdde5f9e59ec',
    messagingSenderId: '274695164037',
    projectId: 'bilal-store-237cd',
    storageBucket: 'bilal-store-237cd.appspot.com',
    iosBundleId: 'com.example.bilalStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_CXuX6tsA6HVcELZYqqFkvBd6CLkRXFw',
    appId: '1:274695164037:web:6287934203a496cb9e59ec',
    messagingSenderId: '274695164037',
    projectId: 'bilal-store-237cd',
    authDomain: 'bilal-store-237cd.firebaseapp.com',
    storageBucket: 'bilal-store-237cd.appspot.com',
    measurementId: 'G-3KR952R5E5',
  );
}
